### ISSUE TITLE
Exception occurs when opening extension settings

### ISSUE THREAD

**Issue by SethFalco** [bdaase/noannoyance#22]
Hey! Thanks for maintaining this, it's a nice workaround until GNOME resolve whatever is making this such a pain. ^-^'

I've just installed the extension but ran into an exception when trying to check out the settings. 

Distro: Debian 11
GNOME Shell: 3.38.6
Noannoyance v2: b759d10fd2799bc084007fdd927b62637c3dbd2c (master at time of cloning)

1. Install extension following the steps in `README.md`.
2. Open GNOME Tweaks
3. Navigate to extension settings
4. Click the cog for Noannoyance v2

![image](https://user-images.githubusercontent.com/22801583/180619691-ed934a22-54c3-4581-9bc1-d74384861094.png)

```
TypeError: enableIgnorelistBox.append is not a function

Stack trace:
  buildPrefsWidget@/home/seth/.local/share/gnome-shell/extensions/noannoyance@daase.net/prefs.js:49:25
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

---

Despite this, I'm able to enable the extension and it appears to work just fine. 👍🏾 
I just can't check out the settings for it.

![image](https://user-images.githubusercontent.com/22801583/180619696-4064f16e-0752-44f7-8b9f-ca58fd220a0c.png)

**Comment by bdaase** [comment]
Yeah, this expected because this extension requires GNOME version 40+ (we can't easily support pre and post version 40 due to the Gtk 3 -> 4 gnome-shell upgrade).

https://github.com/bdaase/noannoyance/commit/0a3361ad1f7d20a053f742fc4c8fd573075c492a is the last commit that should work for pre GNOME 40 gnome-shell versions.
