### ISSUE TITLE
Blacklist Apps

### ISSUE THREAD

**Issue by jeroen7s** [bdaase/noannoyance#8]
For 99% of the apps I want to allow them to steal my focus, and always pop-up, but for some apps I want to get a pop-up message instead.

most importantly for Microsoft Teams, their notification system bypasses dbus, and thus steals focus whenever a notification pops up.
Which means every 15 minutes my typing stops responding because I got a notification for a message that stole my focus.

**Comment by BjoernDaase** [comment]
Thanks for taking time to report this!  
I knew that this request would come at some point. I will try to have a look into it when time permits.

**Comment by haxoc** [comment]
Same thing happens with Signal and Slack.

**Comment by Syzygianinfern0** [comment]
Any updates on this? Similar behavior for Telegram Desktop and Teams on a daily basis :cry:

**Comment by haxoc** [comment]
On Signal there is an option in the settings, which solves the issue.
![here is a screenshot](https://user-images.githubusercontent.com/46831897/100699182-32798a80-3392-11eb-9ff7-a3dbf054ea32.png)

**Comment by skoruppa** [comment]
One more request for this. Native Microsoft Teams is not usable with your extension :(

**Comment by MostHated** [comment]
This happens to me as well, but with Telegram.

**Comment by skoruppa** [comment]
It was really irritating for me so I tried to implemented this by myself ;) Pull request linked above. 

It would be nice if someone else could test this

**Comment by Syzygianinfern0** [comment]
> It was really irritating for me so I tried to implemented this by myself ;) Pull request linked above.
> 
> It would be nice if someone else could test this

![image](https://user-images.githubusercontent.com/31875325/124484322-ecbdee00-ddc8-11eb-87fe-a85feb3a6423.png)

**Comment by skoruppa** [comment]
Thanks @Syzygianinfern0 for checking. If we could make a list of wm_classes that should be blacklisted (I already heard about slack, skype, telegram, and teams) I think we can include them all in a finished version ;)

**Comment by Syzygianinfern0** [comment]
I do use Slack on a daily basis and it does not pose this problem. For me, it is just Telegram (`TelegramDesktop`) and Teams (`Microsoft Teams - Preview`). I do not use Skype, nor do I know anyone else who does, so I cannot test it 😅. Just these two are the problem.

**Comment by bernkat** [comment]
Any updates on this issue? I would really like the ability to blacklist Telegram Desktop.

**Comment by Syzygianinfern0** [comment]
You can build it yourself from this PR: #12
